spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
spring.application.name=ShareWhere

spring.datasource.url=${DB_URL:jdbc:sqlserver://default-url}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.cloud.azure.storage.blob.account-name=${AZURE_ACCOUNT_NAME}
spring.cloud.azure.storage.blob.account-key=${AZURE_ACCOUNT_KEY}
spring.cloud.azure.storage.blob.container-name=images

spring.jpa.hibernate.ddl-auto=update

spring.security.jwt.secret-key=${JWT_SECRET_KEY:default-secret}

management.endpoints.web.exposure.include=health,info
management.endpoint.env.enabled=false
management.endpoint.beans.enabled=false